//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.03 at 01:55:38 PM CEST 
//


package statistics;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="gamesPlayed" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="averageTurns" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="playerMode" maxOccurs="5">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="wins" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="losses" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="Human"/>
 *                       &lt;enumeration value="Optimal"/>
 *                       &lt;enumeration value="Greedy"/>
 *                       &lt;enumeration value="Defensive"/>
 *                       &lt;enumeration value="Random"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gamesPlayed",
    "averageTurns",
    "playerMode"
})
@XmlRootElement(name = "statistics")
public class Statistics {

    @XmlElement(required = true)
    protected BigInteger gamesPlayed;
    @XmlElement(required = true)
    protected BigInteger averageTurns;
    @XmlElement(required = true)
    protected List<Statistics.PlayerMode> playerMode;

    /**
     * Gets the value of the gamesPlayed property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGamesPlayed() {
        return gamesPlayed;
    }

    /**
     * Sets the value of the gamesPlayed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGamesPlayed(BigInteger value) {
        this.gamesPlayed = value;
    }

    /**
     * Gets the value of the averageTurns property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAverageTurns() {
        return averageTurns;
    }

    /**
     * Sets the value of the averageTurns property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAverageTurns(BigInteger value) {
        this.averageTurns = value;
    }

    /**
     * Gets the value of the playerMode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the playerMode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlayerMode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Statistics.PlayerMode }
     * 
     * 
     */
    public List<Statistics.PlayerMode> getPlayerMode() {
        if (playerMode == null) {
            playerMode = new ArrayList<Statistics.PlayerMode>();
        }
        return this.playerMode;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="wins" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="losses" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *       &lt;/sequence>
     *       &lt;attribute name="name">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="Human"/>
     *             &lt;enumeration value="Optimal"/>
     *             &lt;enumeration value="Greedy"/>
     *             &lt;enumeration value="Defensive"/>
     *             &lt;enumeration value="Random"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "wins",
        "losses"
    })
    public static class PlayerMode {

        @XmlElement(required = true, defaultValue = "0")
        protected BigInteger wins;
        @XmlElement(required = true, defaultValue = "0")
        protected BigInteger losses;
        @XmlAttribute(name = "name")
        protected String name;

        /**
         * Gets the value of the wins property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getWins() {
            return wins;
        }

        /**
         * Sets the value of the wins property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setWins(BigInteger value) {
            this.wins = value;
        }

        /**
         * Gets the value of the losses property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getLosses() {
            return losses;
        }

        /**
         * Sets the value of the losses property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setLosses(BigInteger value) {
            this.losses = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }

}
